import { useState, useEffect } from 'react';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '../src/theme';
import Head from 'next/head'
import Header from "./header";
import { useRouter } from 'next/router';
import { Box, Divider, Toolbar } from '@mui/material';
import { Link as MUILink } from '@mui/material';

function Layout({ children } : { children: any}) {
  const { asPath } = useRouter();
  const isHome = (asPath === '/');

  return (
    <>
      <Head>
        <title>Gerador de Tudo</title>
        <meta name="format-detection" content="telephone=no"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
        <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Gerador de Tudo" />
        <meta property="og:locale" content="pt-br" />
        <meta property="og:image" content="/cover.jpg"/>
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
          <Header isHome={isHome}/>
          <Box>
            <Box component="main">
              <Toolbar/>
              {children}
              <Divider sx={{mt: 5}}/>
              <Box sx={{p: 2, display: 'flex', justifyContent: 'center'}}>
                Gil Vieira &copy; { new Date().getFullYear()}{' - '}<MUILink color="secondary" href="/pages/termos-de-uso">Termos de Uso</MUILink>{' - '}<MUILink color="secondary" href="/pages/politica-de-privacidade">Politica de Privacidade</MUILink>
              </Box>
            </Box>
          </Box>
      </ThemeProvider>
    </>
  )
}

export default Layout;
