import { useState, useEffect } from 'react';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '../src/theme';
import Head from 'next/head'
import Sidebar from "./sidebar";
import Header from "./header";
import { useRouter } from 'next/router';
import { Box, Divider, Drawer, Toolbar } from '@mui/material';

function Layout({ children } : { children: any}) {
  const { asPath } = useRouter();
  const isHome = (asPath === '/');
  const [mobileOpen, setMobileOpen] = useState(false);
  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };
  const drawerWidth = 250;

  const [menuItems, setMenuItems] = useState<any[]>([]);

  useEffect(() => {
    fetchData();
  }, [])

  const fetchData = () => {
    fetch('/api/menu')
      .then((res) => res.json())
      .then((data) => {
        setMenuItems(data)
      })
  };


  return (
    <>
      <Head>
        <title>Gerador de Tudo</title>
        <meta name="format-detection" content="telephone=no"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
        <link rel="icon" href="/favicon.ico" type="image/x-icon"/>
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Gerador de Tudo" />
        <meta property="og:locale" content="pt-br" />
        <meta property="og:image" content="/cover.jpg"/>
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
          <Header isHome={isHome} isMenuOpen={mobileOpen} handleMenu={handleDrawerToggle}/>
          <Box sx={{ display: 'flex' }}>
            <Box component="nav" sx={{ width: { lg: drawerWidth }, flexShrink: { lg: 0 } }}>
              <Drawer
                variant="temporary"
                open={mobileOpen}
                onClose={handleDrawerToggle}
                ModalProps={{
                  keepMounted: true
                }}
                sx={{
                  display: { xs: 'block', lg: 'none' },
                  '& .MuiDrawer-paper': { boxSizing: 'border-box', width: drawerWidth },
                }}
              >
              <Sidebar clickLink={handleDrawerToggle} menuItems={menuItems} />
              </Drawer>
              <Drawer
                open
                variant="permanent"
                sx={{
                  display: { xs: 'none', lg: 'block' },
                  '& .MuiDrawer-paper': { boxSizing: 'border-box', width: drawerWidth },
                }}
                >
                <Sidebar clickLink={() => {}} menuItems={menuItems} />
                </Drawer>
            </Box>
            <Box component="main" sx={{ flexGrow: 1, width: { lg: `calc(100% - ${drawerWidth}px)` } }}>
              <Toolbar/>
              {children}
              <Divider sx={{mt: 5}}/>
              <Box sx={{p: 2, display: 'flex', justifyContent: 'center'}}>Gil Vieira &copy; { new Date().getFullYear()}</Box>
            </Box>
          </Box>
      </ThemeProvider>
    </>
  )
}

export default Layout;
